-- Warehouses
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (1, 'Nuveen New York AMT-Free Quality Municipal', '27011 Pankratz Crossing');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (2, '1347 Property Insurance Holdings, Inc.', '0565 Brentwood Circle');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (3, 'VictoryShares US Discovery Enhanced Volatility Wtd ETF', '93 Doe Crossing Road');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (4, 'GSV Capital Corp', '188 Kedzie Crossing');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (5, 'Universal Health Services, Inc.', '56 Blue Bill Park Plaza');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (6, 'J P Morgan Chase & Co', '515 Continental Way');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (7, 'Staples, Inc.', '6651 Westend Place');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (8, 'Loncar Cancer Immunotherapy ETF', '4163 Hauk Drive');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (9, 'CubeSmart', '409 Prairieview Park');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (10, 'DISH Network Corporation', '62 Hoard Road');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (11, 'Biogen Inc.', '718 Aberg Park');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (12, 'Sucampo Pharmaceuticals, Inc.', '57 Vernon Crossing');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (13, 'Gabelli Multi-Media Trust Inc. (The)', '44045 International Junction');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (14, 'BLDRS Asia 50 ADR Index Fund', '3 Rigney Alley');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (15, 'Hudson Technologies, Inc.', '2574 Homewood Court');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (16, 'Noodles & Company', '5 Larry Way');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (17, 'CBOE Holdings, Inc.', '15890 Scoville Pass');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (18, 'Hill-Rom Holdings Inc', '000 Oak Valley Circle');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (19, 'Aevi Genomic Medicine, Inc.', '493 Jackson Crossing');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (20, 'Progenics Pharmaceuticals Inc.', '45868 Lukken Way');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (21, 'Douglas Emmett, Inc.', '22 Bartelt Circle');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (22, 'PC Connection, Inc.', '19 Petterle Alley');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (23, 'Western Alliance Bancorporation', '09949 Pearson Parkway');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (24, 'Sterling Construction Company Inc', '83 Talisman Alley');
insert into WAREHOUSE (warehouse_id, warehouse_name, address) values (25, 'NMI Holdings Inc', '5295 Dryden Parkway');

-- Products
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (1, 'Milk - Chocolate 500ml', 79.13, 14, 1);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (2, 'Lid - 3oz Med Rec', 88.62, 97, 2);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (3, 'Wine - Tribal Sauvignon', 78.91, 10, 3);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (4, 'Milk 2% 500 Ml', 55.34, 1, 4);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (5, 'Tia Maria', 12.09, 68, 5);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (6, 'Halibut - Whole, Fresh', 46.4, 52, 6);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (7, 'Bread - Pita', 71.36, 74, 7);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (8, 'Tumeric', 31.67, 28, 8);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (9, 'Fond - Chocolate', 7.88, 62, 9);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (10, 'Flower - Potmums', 62.6, 64, 10);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (11, 'Mix - Cocktail Strawberry Daiquiri', 20.57, 61, 11);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (12, 'Cabbage Roll', 72.52, 38, 12);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (13, 'Cookie - Oreo 100x2', 45.21, 59, 13);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (14, 'Cookie Dough - Double', 39.78, 35, 14);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (15, 'Wine - Ruffino Chianti', 40.81, 32, 15);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (16, 'Tea - Lemon Green Tea', 65.93, 21, 16);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (17, 'Vinegar - White Wine', 59.09, 57, 17);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (18, 'The Pop Shoppe - Root Beer', 72.34, 97, 18);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (19, 'Lettuce - Green Leaf', 1.76, 31, 19);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (20, 'Pop - Club Soda Can', 97.65, 15, 20);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (21, 'Compound - Orange', 48.39, 15, 21);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (22, 'Shrimp - Tiger 21/25', 71.63, 22, 22);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (23, 'Noodles - Cellophane, Thin', 25.18, 66, 23);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (24, 'Chocolate - Sugar Free Semi Choc', 79.03, 33, 24);
insert into PRODUCT (product_id, product_name, price, quantity, warehouse_id) values (25, 'Nut - Peanut, Roasted', 4.01, 99, 25);
